local wk = require("which-key")
wk.add({
{ "<leader>d", desc = "duplicate file" },
{ "<leader>p", desc = "toggle theme" },
{ "<leader>u", desc = "open url" },
{ "<leader>z", desc = "floating terminal" },
{ "<leader>f", desc = "fzf" },
{ "<leader>g", desc = "grep" },
{ "<leader>G", desc = "grep under cursor" },
{ "<leader>x", desc = "chmod +x" },
{ "<leader>t", desc = "view files" },
{ "<leader>R", desc = "reload config" },
{ "<leader>vs", desc = "vsplit next buf" },
{ "<leader>w", desc = "write" },
{ "<leader>W", desc = "toggle wrap" },
{ "<leader>q", desc = "close this buffer" },
{ "<leader>Q", desc = "close other buffers" },
{ "<leader>U", desc = "close ALL buffers" },
{ "<leader>nn", desc = "toggle relative numbers" },
{ "<leader>T", desc = "pin buffer" },
{ "<leader>F", desc = "fzf opts" },
})
