cursor            #97693c
cursor_text_color #6e3142

foreground	#c77a8d
background	#523312
selection_foreground  #6c4a27
selection_background  #eabb8f
url_color             #ab888f

#: black 000000 767676
color0  #a9808a
color8  #746064
#: red cc0403 f2201f
color1  #b4b3b3
color9  #e7e6e6
#: green 19cb00 23fd00
color2  #dab3bb
color10 #66494f
#: yellow cecb00 fffd00
color3  #523312
color11 #6c4a27
#: blue 0d73cc 1a8fff
color4  #d9899d
color12 #c77a8d
#: magenta cb1ed1 fd28ff
color5  #bb979e
color13 #ab888f
#: cyan 0dcdcd 14ffff
color6  #c3986e
color14 #b28960
#: white dddddd ffffff
color7  #907f82
color15 #ae9fa1

mark1_foreground #ffadc0
mark1_background #7d3d4e
mark2_foreground #e1bac2
mark2_background #66494f
mark3_foreground #eabb8f
mark3_background #6c4a27

active_tab_foreground #907f82
active_tab_background #c77a8d
inactive_tab_foreground #dd8da0
inactive_tab_background  #bb979e

active_border_color #c77a8d
inactive_border_color #ae9fa1
# bell_border_color #ff5a00
