cursor            #715f9e
cursor_text_color #004a68

foreground	#5b97bc
background	#3d3556
selection_foreground  #544c6e
selection_background  #2a3c48
url_color             #8193a1

#: black 000000 767676
color0  #374a55
color8  #606870
#: red cc0403 f2201f
color1  #ffffff
color9  #ffffff
#: green 19cb00 23fd00
color2  #2a3c48
color10 #415360
#: yellow cecb00 fffd00
color3  #3d3556
color11 #544c6e
#: blue 0d73cc 1a8fff
color4  #6ba7cd
color12 #5b97bc
#: magenta cb1ed1 fd28ff
color5  #90a3b1
color13 #8193a1
#: cyan 0dcdcd 14ffff
color6  #a59bc1
color14 #958bb1
#: white dddddd ffffff
color7  #7d848a
color15 #9fa3a8

mark1_foreground #8fcbf2
mark1_background #075779
mark2_foreground #b4c7d5
mark2_background #415360
mark3_foreground #c9bee6
mark3_background #544c6e

active_tab_foreground #004a68
active_tab_background #5b97bc
inactive_tab_foreground #6fabd1
inactive_tab_background #003f59

active_border_color #5b97bc
inactive_border_color #004a68
# bell_border_color #ff5a00
