cursor            #3d7988
cursor_text_color #88161d

foreground	#ef6360
background	#00404c
selection_foreground  #055968
selection_background  #602927
url_color             #c77d78

#: black 000000 767676
color0  #5d3535
color8  #7a5e5c
#: red cc0403 f2201f
color1  #524355
color9  #89708e
#: green 19cb00 23fd00
color2  #602927
color10 #7d3f3c
#: yellow cecb00 fffd00
color3  #00404c
color11 #055968
#: blue 0d73cc 1a8fff
color4  #ff7571
color12 #ef6360
#: magenta cb1ed1 fd28ff
color5  #d98b87
color13 #c77d78
#: cyan 0dcdcd 14ffff
color6  #69aaba
color14 #599aaa
#: white dddddd ffffff
color7  #987d7b
color15 #b39e9c

mark1_foreground #ffb0ab
mark1_background #992427
mark2_foreground #ffb0ab
mark2_background #7d3f3c
mark3_foreground #8dcedf
mark3_background #055968

active_tab_foreground #88161d
active_tab_background #ef6360
inactive_tab_foreground #ff7c78
inactive_tab_background #780713

active_border_color #ef6360
inactive_border_color #88161d
# bell_border_color #ff5a00
