cursor            #ad6027
cursor_text_color #792741

foreground            #7a4315
background            #c77a8d
selection_foreground  #9c2d4f
selection_background  #612637
url_color             #c77a8d

#: black 000000 767676
color0  #6d401e
color8  #81634d
#: red cc0403 f2201f
color1  #eccab6
color9  #ffffff
#: green 19cb00 23fd00
color2  #612637
color10 #7d3d4e
#: yellow cecb00 fffd00
color3  #5e2d00
color11 #7a4315
#: blue 0d73cc 1a8fff
color4  #e9809b
color12 #d7718c
#: magenta cb1ed1 fd28ff
color5  #d9899c
color13 #c77a8d
#: cyan 0dcdcd 14ffff
color6  #d7905c
color14 #c5814e
#: white dddddd ffffff
color7  #9c7d68
color15 #b59f91

mark1_foreground #ffadc0
mark1_background #89334d
mark2_foreground #ffadc0
mark2_background #7d3d4e
mark3_foreground #ffb37d
mark3_background #7a4315

active_tab_foreground #792741
active_tab_background #d7718c
inactive_tab_foreground #ee849f
inactive_tab_background #6b1c36

active_border_color #d7718c
inactive_border_color #792741
# bell_border_color #ff5a00
