#!/usr/bin/env bash
back="$(cat $HOME/IX-config/config/matugen/eDP-1.txt)"

matugen image -t scheme-smart --prefer less-saturation  -m dark --contrast -1 -r gaussian -v "$back" &  

awww img --transition-type wipe --transition-duration 1.0 --filter CatmullRom --transition-fps 78 --transition-angle 180 --transition-bezier .97,.03,.02,.98 -o "eDP-1" "$back"

while [ ! -f ~/.cache/wal/krita.colors ]; do
	sleep 0.1
done

# pkill swaybg
# swaybg -m fill -i "$back" &
# hyprctl hyprpaper wallpaper 'eDP-1, $back'
# killall hyprpaper
# pywalfox update 
# hyprpaper &
